### ISSUE TITLE
Creating the configure executable doesn't work

### ISSUE THREAD

**Issue by Maaarcocr** [zetavm/zetavm#95] opened 2017-08-29 18:51 UTC
Command to create the configure executable:
```
autoconf configure.ac > configure  
```
The error I get when running it:
```
./configure --with-sdl2
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
./configure: line 2282: syntax error near unexpected token `SDL,'
./configure: line 2282: `    PKG_CHECK_MODULES(SDL, sdl2 >= 2.0.0, CXXFLAGS="${CXXFLAGS} -DHAVE_SDL2")'
```

**Comment by krypt-n** [comment] 2017-08-29 19:28
I can't reproduce this with GNU autoconf 2.69 and the produced file is virtually identical to the one that is checked into the repo. Google seems to suggest that you may be missing `pkg-config`, could you check if you have that installed?

**Comment by maximecb** [comment] 2017-08-29 22:36
I think that @krypt-n is right. There is also a dependency on `pkg-config`. I will update the README.

**Comment by maximecb** [comment] 2017-08-29 22:38
Updated the README.

**Closed by maximecb** 2017-08-29 22:38 UTC
Labels: bug
